const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
async function run(o={}){let handler,init,jenkinsReads=0;const entity='component:default/demo';const body=v=>({ok:true,body:new ReadableStream({start(c){c.enqueue(Buffer.from(JSON.stringify(v)));c.close();}})});
const services={config:{getConfig:()=>({getConfigArray:()=>[{getString:k=>({entityRef:o.bindingRef||entity,jobFullName:o.bindingJob||`apps/${o.alias||'demo'}/main`})[k],getOptionalString:k=>o.branch}],getString:k=>({baseUrl:'http://jenkins',publicUrl:'https://jenkins.example',folder:'apps',username:'reader',apiKey:'secret'})[k]})},logger:{warn(){}},httpRouter:{use(){}},httpAuth:{credentials:async()=>{if(o.anonymous){const e=Error();e.name='AuthenticationError';throw e;}return {};}},auth:{getPluginRequestToken:async()=>({token:'catalog-token'})},discovery:{getBaseUrl:async()=> 'http://catalog'}};
const context={URL,Buffer,AbortSignal,Date,module:{exports:{}},fetch:async url=>{if(url.startsWith('http://catalog'))return {ok:!o.denied,json:async()=>({metadata:{annotations:{'jenkins.io/job-full-name':o.job||'apps/demo/main'}}})};jenkinsReads++;if(o.unavailable)return {ok:false};if(url.includes('tree=builds'))return body({builds:[{number:2,result:'SUCCESS',building:!!o.running}]});if(url.includes('/execution/node/1/wfapi/describe'))return body({id:'1',stageFlowNodes:[{id:'10',name:'Shell Script',_links:{log:{href:'https://untrusted.invalid'}}}]});if(url.includes('/execution/node/10/wfapi/log'))return body({nodeId:o.wrongNode?'11':'10',text:o.longLog?'x'.repeat(70000):'\u001b[31mhello secret <script>unsafe</script>',hasMore:false});if(url.includes('wfapi'))return body({id:o.wrongBuild?3:2,stages:[{id:1,name:'Build',status:o.badStatus?'madeup':o.running?'IN_PROGRESS':o.failed?'FAILED':'SUCCESS',durationMillis:1000}]});return body({building:!!o.running,result:o.failed?'FAILURE':'SUCCESS',duration:2000,timestamp:Date.now()-2000,actions:[{lastBuiltRevision:{SHA1:'a'.repeat(40)}}]});},require:n=>{if(n==='express')return{Router:()=>({get:(p,h)=>handler=h})};if(n==='@backstage/backend-plugin-api')return{coreServices:{},createBackendPlugin:d=>{d.register({registerInit:a=>init=a.init(services)});return d;}};throw Error(n);}};
vm.runInNewContext(fs.readFileSync(require.resolve('../index.cjs'),'utf8'),context);await init;const out={status:200};const res={status:n=>{out.status=n;return res;},json:v=>{out.body=v;return res;},set:()=>res,end:()=>res};await handler({path:o.logs?'/logs':'/progress',query:{entity:o.entity||entity,...(o.build?{build:o.build}:{}),...(o.logs?{stage:o.stage||'1'}:{}),...(o.node?{node:o.node}:{})}},res);return {...out,jenkinsReads};}
test('Anonymous and catalog-denied requests never reach Jenkins',async()=>{for(const o of [{anonymous:true},{denied:true}]){const r=await run(o);assert.equal(r.status,o.anonymous?401:403);assert.equal(r.jenkinsReads,0);}});
test('Job and parameter injection fail before Jenkins',async()=>{for(const o of [{job:'apps/other/main'},{job:'apps/../../admin/main'},{entity:'../../admin'},{build:'2/../../admin'}]){const r=await run(o);assert.ok([400,403].includes(r.status));assert.equal(r.jenkinsReads,0);}});
test('Running, completed and failed stages remain distinct',async()=>{for(const o of [{},{running:true},{failed:true}]){const r=await run(o);assert.equal(r.status,200);assert.equal(r.body.status,o.running?'IN_PROGRESS':o.failed?'FAILURE':'SUCCESS');assert.equal(r.body.stages[0].status,o.running?'IN_PROGRESS':o.failed?'FAILED':'SUCCESS');assert.equal(r.body.commit,'a'.repeat(40));assert.match(r.body.jenkinsUrl,/https:\/\/jenkins.example/);}});
test('Unavailable and malformed evidence never imply success',async()=>{for(const o of [{unavailable:true},{wrongBuild:true},{badStatus:true}])assert.equal((await run(o)).status,503);assert.equal((await run({build:'99'})).status,404);});
test('Administrator alias permits only its exact folder and main branch',async()=>{assert.equal((await run({alias:'legacy-job',job:'apps/legacy-job/main'})).status,200);for(const job of ['other/legacy-job/main','apps/legacy-job/develop','apps/unrelated/main']){const r=await run({alias:'legacy-job',job});assert.equal(r.status,403);assert.equal(r.jenkinsReads,0);}});
test('Stage logs are bound to the authorized build and its reported nodes',async()=>{const r=await run({logs:true,build:'2'});assert.equal(r.status,200);assert.equal(r.body.node,'10');assert.equal(r.body.text,'hello [REDACTED] <script>unsafe</script>');assert.match(r.body.jenkinsUrl,/\/2\/console$/);assert.equal((await run({logs:true,build:'2',node:'999'})).status,404);assert.equal((await run({logs:true,build:'2',stage:'999'})).status,404);for(const o of [{node:'../admin'},{stage:'../admin'}]){const x=await run({logs:true,build:'2',...o});assert.equal(x.status,400);assert.equal(x.jenkinsReads,0);}});
test('Log previews are bounded and malformed node evidence fails closed',async()=>{const r=await run({logs:true,build:'2',longLog:true});assert.equal(r.body.text.length,65536);assert.equal(r.body.truncated,true);assert.equal((await run({logs:true,build:'2',wrongNode:true})).status,503);assert.equal((await run({logs:true})).status,400);for(const o of [{anonymous:true},{denied:true}]){const r=await run({logs:true,build:'2',...o});assert.equal(r.status,o.anonymous?401:403);assert.equal(r.jenkinsReads,0);}});

test('Explicit bindings support arbitrary namespaces, nested jobs and branches',async()=>{const r=await run({entity:'component:payments/payments-api',bindingRef:'component:payments/payments-api',bindingJob:'division/team/payments/develop',job:'division/team/payments/develop',branch:'develop'});assert.equal(r.status,200);assert.equal(r.body.branch,'develop');assert.equal((await run({entity:'component:other/demo'})).status,403);});
