community:
  enabled: true
  buildNumber: '26.9.0.129388'
OpenShift:
  enabled: true
  createSCC: false
initSysctl:
  enabled: false
initFs:
  enabled: false
gvisor:
  enabled: false
monitoringPasscodeSecretName: sonar-bootstrap
monitoringPasscodeSecretKey: monitoring
jdbcOverwrite:
  enabled: true
  jdbcUrl: jdbc:postgresql://sonar-db:5432/sonar
  jdbcUsername: sonar
  jdbcSecretName: sonar-bootstrap
  jdbcSecretPasswordKey: database
persistence:
  enabled: true
  size: 10Gi
resources:
  requests:
    cpu: 500m
    memory: 4Gi
    ephemeral-storage: 1Gi
  limits:
    cpu: '4'
    memory: 8Gi
    ephemeral-storage: 5Gi
