apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-db
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-db
  namespace: sonarqube
spec:
  selector:
    app: sonar-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-db
  namespace: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonar-db
  template:
    metadata:
      labels:
        app: sonar-db
    spec:
      containers:
      - name: postgresql
        image: registry.redhat.io/rhel9/postgresql-16@sha256:521a45716a9aa286b2330da6d6d1d4f684a140a38ffd00a7f59a9751791cd106
        env:
        - name: POSTGRESQL_USER
          value: sonar
        - name: POSTGRESQL_DATABASE
          value: sonar
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonar-bootstrap
              key: database
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgsql/data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonar-db
