kubernetes:
  serviceLocatorMethod: {type: multiTenant}
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: application-cluster
          url: https://kubernetes.default.svc
          authProvider: serviceAccount
          skipTLSVerify: false
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          skipMetricsLookup: true
          dashboardUrl: https://OPENSHIFT_CONSOLE_HOST
          dashboardApp: openshift
  customResources:
    - {group: route.openshift.io, apiVersion: v1, plural: routes}
