apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesh-system
resources:
  - adapter.yaml
configMapGenerator:
  - name: kiali-compat
    files:
      - server.py=kiali_compat.py
