import React,{useEffect,useState} from 'react';
import {useEntity} from '@backstage/plugin-catalog-react';
import {stringifyEntityRef} from '@backstage/catalog-model';
import {useApi,discoveryApiRef,fetchApiRef} from '@backstage/core-plugin-api';
export const isVaultHealthAvailable=(e:any)=>Boolean(e.metadata.annotations?.['vault-health.io/vault-binding']);
const checks:Record<string,[string,string]>={connection:['Vault connection','Provider availability over verified TLS.'],authentication:['Workload authentication','Evidence that the application identity authenticated for delivery.'],delivery:['Secret delivery','Evidence that the configured delivery mechanism synchronized credentials.'],consumption:['Application consumption','Last functional application acceptance for the current deployment.'],rotation:['Rotation verification','A coordinated credential change followed by successful application acceptance.']};
export function VaultHealth(){
 const {entity}=useEntity(),discovery=useApi(discoveryApiRef),fetcher=useApi(fetchApiRef);
 const [data,setData]=useState<any>(),[error,setError]=useState(''),[rev,setRev]=useState(0);
 const ref=stringifyEntityRef(entity);
 useEffect(()=>{let active=true;async function load(){try{const r=await fetcher.fetch(`${await discovery.getBaseUrl('vault-health')}/vault?entity=${encodeURIComponent(ref)}`);if(!r.ok)throw Error('Vault health evidence is unavailable or access was denied.');const value=await r.json();if(active){setData(value);setError('');}}catch(e){if(active){setData(undefined);setError((e as Error).message);}}}load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[ref,discovery,fetcher,rev]);
 return <section className="vault-details" aria-label="Vault integration"><style>{`.vault-details{padding:28px;border:1px solid #dedbd9;border-radius:12px;background:#fff;color:#292524}.vault-details h2{font-size:28px;margin:8px 0}.vault-details .eyebrow{font-size:12px;letter-spacing:1.4px;color:#746c68}.vault-details .heading{display:flex;justify-content:space-between;gap:20px;align-items:center}.vault-details button{font:inherit;border:1px solid #b8b0ab;background:#fff;border-radius:6px;padding:8px 14px;cursor:pointer}.vault-details button:focus-visible{outline:3px solid #3274ba}.vault-details table{width:100%;border-collapse:collapse;margin:24px 0}.vault-details th,.vault-details td{text-align:left;padding:16px 12px;border-bottom:1px solid #e5e2e0;vertical-align:top}.vault-details th{background:#f5f3f2}.vault-details .status{font-weight:600}.vault-details .healthy{color:#216343}.vault-details .unknown{color:#6b5b32}.vault-details .degraded,.vault-details .unavailable{color:#aa2323}.vault-details .note{padding:16px;border-left:3px solid #8c7770;background:#faf8f7}.vault-details .table-wrap{overflow-x:auto}`}</style>
 <div className="heading"><div><span className="eyebrow">APPLICATION SECRETS</span><h2>Vault integration</h2></div><button onClick={()=>setRev(n=>n+1)}>Refresh</button></div>
 <p>Configuration and delivery evidence for <strong>{entity.metadata.title||entity.metadata.name}</strong>. Secret values and Vault credentials are never retrieved by this view.</p>
 <p><strong>Catalog binding:</strong> {entity.metadata.annotations?.['vault-health.io/vault-binding']} · <strong>Component:</strong> {ref}</p>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading integration evidence…</p>}
 {data&&<>{data.stale&&<p role="alert" className="note">Evidence is stale. Refreshing this page does not make old evidence current.</p>}<div className="table-wrap"><table><thead><tr><th>Check</th><th>Status</th><th>Last successful evidence</th></tr></thead><tbody>{Object.entries(checks).map(([key,[title,description]])=><tr key={key}><td><strong>{title}</strong><div style={{fontSize:13,marginTop:6}}>{description}</div></td><td className={`status ${data.checks[key]?.status||'unknown'}`}>{data.checks[key]?.status||'unknown'}</td><td>{data.checks[key]?.lastSuccessAt?new Date(data.checks[key].lastSuccessAt).toLocaleString():'Not recorded'}</td></tr>)}</tbody></table></div><p>Report collected: {new Date(data.observedAt).toLocaleString()}. Updates every minute.</p></>}
 <p className="note">Unknown means evidence has not been recorded. A successful provider connection alone does not prove delivery, application consumption or rotation. Consumption timestamps refer to functional acceptance, not a new login on every refresh.</p>
 <p>See the application TechDocs for the secret delivery workflow and operator recovery procedure.</p>
 </section>;
}
