import React,{useCallback,useEffect,useState} from 'react';
import {useEntity} from '@backstage/plugin-catalog-react';
import {stringifyEntityRef} from '@backstage/catalog-model';
import {useApi,discoveryApiRef,fetchApiRef,configApiRef} from '@backstage/core-plugin-api';
export const isServiceNowAvailable=()=>true;
const card:React.CSSProperties={border:'1px solid #dce1e8',borderRadius:14,padding:24,background:'#fff',color:'#172b4d',boxShadow:'0 3px 12px #132b4d08'};
const control:React.CSSProperties={padding:'10px 14px',border:'1px solid #aeb8c7',borderRadius:8,font:'inherit'};
export function ServiceNowInfrastructure(){
 const {entity}=useEntity(),ref=stringifyEntityRef(entity),discovery=useApi(discoveryApiRef),fetcher=useApi(fetchApiRef),config=useApi(configApiRef);
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[purpose,setPurpose]=useState(''),[kind,setKind]=useState('project'),[hours,setHours]=useState(4),[updated,setUpdated]=useState('');
 const enabled=(config.getOptionalStringArray('serviceNowInfrastructure.entities')||[]).includes(ref);
 const call=useCallback(async(path:string,body?:any)=>{const r=await fetcher.fetch(`${await discovery.getBaseUrl('servicenow-infrastructure')}${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,entity:ref})}:undefined);const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;},[ref,fetcher,discovery]);
 const refresh=useCallback(async()=>{try{const data=await call('/requests?entity='+encodeURIComponent(ref));setRows(data.requests);setUpdated(new Date().toLocaleTimeString());setError('');}catch(e){setError((e as Error).message);}},[call,ref]);
 useEffect(()=>{if(!enabled)return;void refresh();const id=setInterval(refresh,15000);return()=>clearInterval(id);},[refresh,enabled]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await call('/requests',{purpose,targetKind:kind,hours});setPurpose('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!enabled)return <div style={card}>Infrastructure requests are not configured for this application.</div>;
 return <section style={{padding:24,maxWidth:1400,margin:'auto',fontFamily:'inherit'}}><header style={{marginBottom:24}}><span style={{color:'#c60025',fontWeight:700,letterSpacing:2,fontSize:12}}>SERVICENOW · INFRASTRUCTURE</span><h1 style={{fontSize:30,margin:'8px 0'}}>Your environment, on request</h1><p>Request a temporary environment. A platform approver reviews it in ServiceNow before provisioning begins.</p></header>
 {error&&<div role="alert" style={{...card,background:'#fff2f1',marginBottom:20}}>{error}</div>}
 <form onSubmit={submit} style={{...card,marginBottom:24}}><h2 style={{marginTop:0}}>New environment</h2><div style={{display:'flex',gap:16,flexWrap:'wrap',alignItems:'end'}}><label style={{flex:'1 1 340px'}}>Business purpose<input required minLength={5} maxLength={500} value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Test the savings API in an isolated sandbox" style={{...control,display:'block',width:'100%',boxSizing:'border-box',marginTop:8}}/></label><label>Environment<select value={kind} onChange={e=>setKind(e.target.value)} style={{...control,display:'block',marginTop:8}}><option value="project">OpenShift project</option><option value="virtual_machine">Virtual machine</option></select></label><label>Lifetime<select value={hours} onChange={e=>setHours(Number(e.target.value))} style={{...control,display:'block',marginTop:8}}>{[1,4,8,24].map(h=><option key={h} value={h}>{h} hours</option>)}</select></label><button disabled={busy} style={{...control,background:'#c60025',color:'white',borderColor:'#c60025'}}>{busy?'Submitting…':'Request environment'}</button></div></form>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>Requests and environments</h2><div><small>{updated&&`Updated ${updated} · `}</small><button style={control} onClick={()=>void refresh()}>Refresh</button></div></div>
 {!rows.length&&<div style={card}>No requests yet. Create your first environment above.</div>}
 <div style={{display:'grid',gap:18}}>{rows.map(r=><article key={r.id} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><a href={r.url} target="_blank" rel="noreferrer" style={{fontWeight:700,color:'#a50020'}}>{r.number}</a><h3 style={{margin:'8px 0'}}>{r.purpose}</h3></div><strong style={{background:'#eef3f8',borderRadius:20,padding:'8px 16px',alignSelf:'start'}}>{r.status}</strong></div><ol style={{display:'flex',gap:28,paddingLeft:20,flexWrap:'wrap',color:'#53647a'}}><li>Requested</li><li>Approval: <strong>{r.approval}</strong></li><li>Provisioning: <strong>{r.fulfillment}</strong></li></ol><p>{r.targetKind==='virtual_machine'?'Virtual machine':'OpenShift project'} · Expires {r.expiresAt}</p>{r.output&&<p>{r.output}</p>}{r.resourceUrl&&<a href={r.resourceUrl} target="_blank" rel="noreferrer">Open environment ↗</a>}{r.fulfillment==='Ready'&&<button style={{...control,marginLeft:16}} onClick={async()=>{if(window.confirm('Delete this temporary environment?')){try{await call('/teardown',{id:r.id});await refresh();}catch(e){setError((e as Error).message);}}}}>Delete environment</button>}</article>)}</div></section>;
}
