import React,{useEffect,useState} from 'react';
import {useEntity} from '@backstage/plugin-catalog-react';
import {stringifyEntityRef} from '@backstage/catalog-model';
import {useApi,discoveryApiRef,fetchApiRef} from '@backstage/core-plugin-api';
export const isPipelineProgressAvailable=(e:any)=>Boolean(e.metadata.annotations?.['jenkins.io/job-full-name']);
const labels:any={SUCCESS:'Passed',FAILED:'Failed',FAILURE:'Failed',ABORTED:'Aborted',UNSTABLE:'Unstable',IN_PROGRESS:'Running',PAUSED_PENDING_INPUT:'Awaiting input',NOT_EXECUTED:'Not run',QUEUED:'Queued'};
const duration=(ms:number)=>`${Math.floor(ms/60000)}m ${Math.floor(ms/1000)%60}s`;
export function PipelineProgress(){const {entity}=useEntity();const discovery=useApi(discoveryApiRef),fetcher=useApi(fetchApiRef);const [data,setData]=useState<any>(),[error,setError]=useState(''),[build,setBuild]=useState(''),[rev,setRev]=useState(0),[loading,setLoading]=useState(false),[logStage,setLogStage]=useState<any>();
useEffect(()=>setLogStage(undefined),[build,entity,data?.number]);
useEffect(()=>{let active=true,timer:any;setData(undefined);async function load(){setLoading(true);try{const base=await discovery.getBaseUrl('ci-progress');const r=await fetcher.fetch(`${base}/progress?entity=${encodeURIComponent(stringifyEntityRef(entity))}${build?'&build='+build:''}`);if(!r.ok)throw Error(r.status===403?'You do not have access to this pipeline.':'Pipeline progress is unavailable. Refresh to retry.');const value=await r.json();if(active){setData(value);setError('');}}catch(e){if(active){setError((e as Error).message);setData(undefined);}}finally{if(active){setLoading(false);timer=setTimeout(load,5000);}}}load();return()=>{active=false;clearTimeout(timer);};},[entity,discovery,fetcher,build,rev]);
return <section className="pipeline-progress" aria-label="Pipeline progress"><style>{`.pipeline-progress{padding:24px;border:1px solid #82929c55;border-radius:12px;margin-bottom:20px}.pipeline-progress h2{margin:4px 0;font-size:25px}.pipeline-progress .header{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.pipeline-progress .controls{display:flex;gap:10px;align-items:center}.pipeline-progress button,.pipeline-progress select{font:inherit;background:transparent;color:inherit;border:1px solid #87959d;border-radius:6px;padding:8px}.pipeline-progress .muted{font-size:13px;opacity:.75}.pipeline-progress .stages{display:flex;gap:34px;padding:28px 16px;list-style:none;margin:22px 0;overflow-x:auto;background:#f6f5f4;border-radius:12px;align-items:stretch}.pipeline-progress .stage{display:flex;flex-direction:column;position:relative;flex:0 0 164px;padding:14px;border:1px solid #d4cfca;border-top:4px solid #87959d;border-radius:24px;background:#fff;min-height:100px}.pipeline-progress .stage-actions{margin-top:auto;padding-top:12px}.pipeline-progress .stage:not(:last-child):after{content:"";position:absolute;left:100%;top:50%;width:35px;height:2px;background:#a8a29e}.pipeline-progress .stage:not(:last-child):before{content:"";position:absolute;left:calc(100% + 27px);top:calc(50% - 4px);border-left:7px solid #a8a29e;border-top:5px solid transparent;border-bottom:5px solid transparent}.pipeline-progress .SUCCESS{border-top-color:#21876b;background:#21876b0c}.pipeline-progress .FAILED,.pipeline-progress .ABORTED{border-top-color:#c74035;background:#c740350c}.pipeline-progress .IN_PROGRESS,.pipeline-progress .PAUSED_PENDING_INPUT{border-top-color:#2476c5;background:#2476c50c}.pipeline-progress .state{display:block;font-weight:600;margin:10px 0}.pipeline-progress .notice{padding:12px;background:#d9982518;border-radius:6px}.pipeline-progress a{color:#267ca2}.pipeline-progress button:focus-visible,.pipeline-progress select:focus-visible{outline:3px solid #2476c5}@media(max-width:600px){.pipeline-progress{padding:16px}.pipeline-progress .controls{flex-wrap:wrap}}`}</style>
<div className="header"><div><span className="muted">JENKINS DELIVERY</span><h2>Pipeline progress</h2></div><div className="controls"><label>Build <select aria-label="Select pipeline build" value={build} onChange={e=>setBuild(e.target.value)}><option value="">Latest</option>{data?.builds?.map((b:any)=><option key={b.number} value={b.number}>#{b.number}</option>)}</select></label><button onClick={()=>setRev(x=>x+1)} disabled={loading}>{loading?'Updating…':'Refresh'}</button></div></div>
{error&&<p role="alert" className="notice">{error}</p>}{!data&&!error&&<p role="status">Loading pipeline stages…</p>}
{data&&<>{data.empty?<p>No builds yet.{data.queued?' A build is queued.':''}</p>:<><p>Build <strong>#{data.number}</strong> · {data.branch} · <code>{data.commit?.slice(0,12)||'Commit unavailable'}</code> · <strong>{labels[data.status]||data.status}</strong> · {duration(data.durationMillis||0)}</p>{data.queued&&<p className="notice">Another build is queued.</p>}<ol className="stages" aria-label="Connected pipeline stages" tabIndex={0}>{data.stages.map((s:any,i:number)=><li className={`stage ${s.status}`} key={s.id}><span className="muted">{i+1}</span><div><strong>{s.name}</strong></div><span className="state">{labels[s.status]||s.status}</span><span className="muted">{duration(s.durationMillis)}</span><div className="stage-actions"><button aria-label={`Logs for ${s.name}`} onClick={()=>setLogStage(s)}>Logs</button></div></li>)}</ol>{!data.stages.length&&<p>No stage data is available yet.</p>}{logStage&&<StageLogs entityRef={stringifyEntityRef(entity)} build={data.number} stage={logStage} onClose={()=>setLogStage(undefined)}/>}<a href={data.jenkinsUrl} target="_blank" rel="noopener noreferrer">Open this build and logs in Jenkins ↗</a></>}<p className="muted">Updates every 5 seconds while this panel is open. Stages appear when Jenkins reports them; missing later stages are not assumed to have passed. Updated {data.observedAt?new Date(data.observedAt).toLocaleTimeString():'just now'}.</p></>}
</section>;
}

function StageLogs({entityRef,build,stage,onClose}:any){
 const discovery=useApi(discoveryApiRef),fetcher=useApi(fetchApiRef);const [data,setData]=useState<any>(),[node,setNode]=useState(''),[error,setError]=useState(''),[rev,setRev]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{setNode('');},[build,stage.id]);
 useEffect(()=>{let active=true;setData(undefined);setError('');setLoading(true);(async()=>{try{const base=await discovery.getBaseUrl('ci-progress');const r=await fetcher.fetch(`${base}/logs?entity=${encodeURIComponent(entityRef)}&build=${build}&stage=${stage.id}${node?'&node='+node:''}`);if(!r.ok)throw Error('Stage logs are unavailable for this selection.');const value=await r.json();if(active)setData(value);}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[entityRef,build,stage.id,node,rev,discovery,fetcher]);
 return <section aria-label="Stage logs" style={{border:'1px solid #82929c66',borderRadius:8,padding:16,marginBottom:20}}><div className="header"><h3 style={{margin:0}}>Build #{build} · {stage.name} logs</h3><div className="controls"><button disabled={loading} onClick={()=>setRev(x=>x+1)}>Refresh logs</button><button onClick={onClose}>Close logs</button></div></div>{loading&&<p role="status">Loading stage logs…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.steps.length>0?<label>Step <select aria-label="Select log step" value={node||data.node} onChange={e=>setNode(e.target.value)}>{data.steps.map((s:any)=><option key={s.id} value={s.id}>{s.name} (#{s.id})</option>)}</select></label>:'Jenkins has not reported a log-bearing step for this stage.'}</p>{data.node&&<pre tabIndex={0} aria-label="Stage log output" style={{maxHeight:360,overflow:'auto',whiteSpace:'pre-wrap',overflowWrap:'anywhere',background:'#142330',color:'#edf3f7',padding:16,borderRadius:6,fontSize:13,lineHeight:1.5}}>{data.text||'No output has been reported for this step.'}</pre>}{data.truncated&&<p className="notice">This is a bounded log preview. Jenkins has more output.</p>}<p className="muted">Logs load on demand. Use Refresh logs for new output.</p><a href={data.jenkinsUrl} target="_blank" rel="noopener noreferrer">Open full build console in Jenkins ↗</a></>}</section>;
}
